# This is the configuration for the DiscordSRV addon.
# Please note that you'll need to have Lands installed and setup.
#
# Lands: https://www.spigotmc.org/resources/53313


# General configuration
general:
  # Default: English (en-US) - no download required.
  # This defines the default language. You can place multiple locales in the plugin's "Language" folder to display different locales depending on the player's locale.
  # You can access translations maintained by the community in our Discord: https://discord.gg/B4MAJVk
  # To access translations, other than en-US, execute /translations in the Discord server.
  language: 'en-US'
  # Date format
  # MM: Month
  # dd: Day of month
  # yyyy: Year
  # hh: hours
  # mm: minutes
  # ss: seconds
  # NOTE: These settings require server reload / restart.
  date-format:
    # Set the time zone for date text outputs.
    # Example: America/Los_Angeles or GMT-8:00
    # List of time zones: https://timezonedb.com/time-zones
    # If empty, it uses the time zone of the machine your server is running on.
    time-zone: ''
    # General format for invites etc.
    # Examples:
    #   American 12-hour format (a = 12 hour format): MM/dd/yyyy hh:mm a
    #   German 24-hour format: dd.MM.yyyy hh:mm
    general: 'MM/dd/yyyy hh:mm a'
    # Format for news messages in the land menu (inbox).
    inbox: 'MMMMM dd'
    # Format used when only a time displayed.
    # Examples:
    #   American 12-hour format (a = 12-hour format): hh:mm a
    #   German 24-hour format: hh:mm
    time_2: 'hh:mm a'

  # Set the format of all economy related displays.
  # NOTE: This setting requires server reload / restart.
  eco-format: '#,###.00'
  # Lets you define the provider to be used for retrieving skins for chat messages in Discord.
  # Relevant for the following modules: chat, lands
  head-provider: 'https://mc-heads.net/avatar/{uuid}'
  # Invite URL to your Discord server. This URL is used in some modules.
  invite-url: "https://discord.gg/YOUR_INVITE"


# Database options
database:
  # MySQL database
  # To use this without issues, your connection limits etc. need to be configured properly in your MySQL server configuration.
  mysql:
    enabled: false
    address: "localhost"
    port: "3306"
    username: "minecraft"
    password: "password"
    database: "discordbridge"

    # It is highly recommended to set a unique table prefix if the plugin shares a database with other plugins or Lands instances.
    table-prefix: "discordbridge_"

  # Optional: Used to forward information to the instance of DiscordBridge that runs the Discord bot.
  # Modules that benefit from this: chat, lands
  redis:
    enabled_2: false
    address_2: "redis://127.0.0.1"
    port_2: 6379
    # Database index. No other plugin should use the same index.
    database-index: 1
    username_2: "default"
    password_2: "password"
    # This should be the name that you configured for this server in your BungeeCord or Velocity config.
    server-name: "server-1"
    # Should be true, if this instance runs the Discord bot.
    master: false

# Configure logging
logging:
  # We might ask you to enable this, when you submit a bugreport.
  debug: false